services:
  db:
    image: postgres:16
    container_name: open-finance-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: openfinance
    ports:
      - "5433:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
